'use strict';

var { NativeModules } = require('react-native');

var RCTModule = NativeModules.BG1AProfileModule

/**
 * @module BG1AProfileModule
 */
module.exports = {

  ACTION_GET_ALL_CONNECTED_DEVICES: RCTModule.ACTION_GET_ALL_CONNECTED_DEVICES,
  
  ACTION_ERROR_BG1A: RCTModule.ACTION_ERROR_BG1A,
  ERROR_NUM_BG1A: RCTModule.ERROR_NUM_BG1A,
  ERROR_DESCRIPTION_BG1A: RCTModule.ERROR_DESCRIPTION_BG1A,

  ACTION_INFO_IDPS: RCTModule.ACTION_INFO_IDPS,
  ACTION_BATTERY_BG1A: RCTModule.ACTION_BATTERY_BG1A,
  INFO_BATTERY_BG1A: RCTModule.INFO_BATTERY_BG1A,

  ACTION_SET_MEASURE_MODE: RCTModule.ACTION_SET_MEASURE_MODE,
  ACTION_GET_BLOOD: RCTModule.ACTION_GET_BLOOD,

  ACTION_STRIP_INSERTION_STATUS: RCTModule.ACTION_STRIP_INSERTION_STATUS,
  STRIP_INSERTION_STATUS: RCTModule.STRIP_INSERTION_STATUS,
  STRIP_CODE_TYPE: RCTModule.STRIP_CODE_TYPE,

  ACTION_MEASURE_RESULT: RCTModule.ACTION_MEASURE_RESULT,
  MEASURE_MODE: RCTModule.MEASURE_MODE,
  MEASURE_RESULT: RCTModule.MEASURE_RESULT, 

  OPERATION_STATUS: RCTModule.OPERATION_STATUS,
  OPERATION_DESCRIBE: RCTModule.OPERATION_DESCRIBE,
  ACTION_SET_DEVICE_CODE: RCTModule.ACTION_SET_DEVICE_CODE,
  ACTION_GET_DEVICE_CODE: RCTModule.ACTION_GET_DEVICE_CODE,
}
