//
//  Am5ProfileModule.m
//  ReactNativeIOSLibrary
//
//  Created by daiqingquan on 2016/12/4.
//  Copyright © 2016年 daiqingquan. All rights reserved.
//

#import "AM5ProfileModule.h"

@implementation AM5ProfileModule


RCT_EXPORT_MODULE()

#pragma mark
#pragma mark - constantsToExport


- (NSDictionary *)constantsToExport
{
    return @{
             @"ACTION_ERROR":kACTION_ERROR,
             @"ERROR_NUM":ERROR_NUM,
             @"ERROR_DESCRIPTION":ERROR_DESCRIPTION,
             @"ACTION_USER_BIND":kACTION_USER_BIND,
             @"ACTION_USER_UNBIND":kACTION_USER_UNBIND,
             @"ACTION_FUNCTION_SUPPORT":kACTION_FUNCTION_SUPPORT,
             @"ACTION_BASIC_INFO":kACTION_BASIC_INFO,
             @"ACTION_MAC_ADDRESS":MAC_ADDRESS,
             @"MAC_ADDRESS":MAC_ADDRESS,
             @"BASIC_BATTSTATUS":BASIC_BATTSTATUS,
             @"BASIC_DEIVCEID":BASIC_DEIVCEID,
             @"BASIC_ENERGE":BASIC_ENERGE,
             @"BASIC_FIRMWAREVERSION":BASIC_FIRMWAREVERSION,
             @"BASIC_MODE":BASIC_MODE,
             @"BASIC_PAIRFLAG":BASIC_PAIRFLAG,
             @"BASIC_REBOOT":BASIC_REBOOT,
             @"ACTION_LIVE_DATA":kACTION_LIVE_DATA,
             @"HEARTRATE":LIVE_DATA_HEARTRATE,
             @"STEP":LIVE_DATA_STEP,
             @"DISTANCES":LIVE_DATA_DISTANCES,
             @"ACTIVETIME":LIVE_DATA_ACTIVETIME,
             @"CALORIE":LIVE_DATA_CALORIE,
             @"ACTION_ACTIVITY_COUNT":kACTION_ACTIVITY_COUNT,
             @"ACTION_SET_TIME":kACTION_SET_TIME,
             @"ACTION_SET_ALARM":kACTION_SET_ALARM,
             @"ACTION_SET_GOAL":kACTION_SET_GOAL,
             @"ACTION_SET_LONG_SIT":kACTION_SET_LONG_SIT,
             @"ACTION_SET_USER_INFO":kACTION_SET_USER_INFO,
             @"ACTION_SET_UNIT":kACTION_SET_UNIT,
             @"ACTION_SET_HAND_WEAR_MODE":kACTION_SET_HAND_WEAR_MODE,
             @"ACTION_SET_UP_HAND_GESTURE":kACTION_SET_UP_HAND_GESTURE,
             @"ACTION_SET_HEART_RATE_INTERVAL":kACTION_SET_HEART_RATE_INTERVAL,
             @"ACTION_SET_HEART_RATE_MEASURE_MODE":kACTION_SET_HEART_RATE_MEASURE_MODE,
             @"ACTION_SET_ONE_KEY_RESET":kACTION_SET_ONE_KEY_RESET,
             @"ACTION_SET_NOT_DISTURB":kACTION_SET_NOT_DISTURB,
             @"ACTION_SET_SPORT_MODE":kACTION_SET_SPORT_MODE,
             @"OPERATION_RESULT":OPERATION_RESULT,
             @"OPERATION_ACTION":OPERATION_ACTION,
             @"ACTION_NOTICE_COMMING_CALL":kACTION_NOTICE_COMMING_CALL,
             @"ACTION_NOTICE_COMMING_CALL_STOP":kACTION_NOTICE_COMMING_CALL_STOP,
             @"ACTION_NOTICE_NEW_MESSAGE":kACTION_NOTICE_NEW_MESSAGE,
             @"ACTION_SYNC_ACTIVITY":kACTION_SYNC_ACTIVITY,
             @"ACTION_SYNC_ACTIVITY_DATA":kACTION_SYNC_ACTIVITY_DATA,
             @"ACTION_SYNC_CONFIG":kACTION_SYNC_CONFIG,
             @"ACTION_SYNC_HEALTH_DATA":kACTION_SYNC_HEALTH_DATA,
             @"ACTION_SYNC_HEALTH_DATA_SPORT":kACTION_SYNC_HEALTH_DATA_SPORT,
             @"ACTION_SYNC_HEALTH_DATA_SLEEP":kACTION_SYNC_HEALTH_DATA_SLEEP,
             @"ACTION_SYNC_HEALTH_DATA_HEART_RATE":kACTION_SYNC_HEALTH_DATA_HEART_RATE,
             @"ACTION_SYNC_HEALTH_DATA_BLOOD_PRESSURE":kACTION_SYNC_HEALTH_DATA_BLOOD_PRESSURE,
             @"OPERATION_STATUS":OPERATION_STATUS,
             @"PROGRESS":PROGRESS,
             @"TYPE":TYPE,
             @"DATA":DATA,
             @"RESULT":RESULT,
             @"ACTION_GET_ALL_CONNECTED_DEVICES":kACTION_ERROR,
             };
};


+ (BOOL)requiresMainQueueSetup
{
    return YES;
}

@end
