import { AM6Module } from '@ihealth/ihealthlibrary-react-native';

export default {
  apis: {
    getAllConnectedDevices:   () => AM6Module.getAllConnectedDevices(),
    getDeviceInfoAndSyncTime: () => AM6Module.getDeviceInfoAndSyncTime(true),
    setUserInfo:              () => AM6Module.setUserInfo([0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], 1, 30, 170, 60),
    setPhonePlatform:         () => AM6Module.setPhonePlatform(),
    notifyMessage:            () => AM6Module.notifyMessage(1660926758875, 1, 1, "This is title", "This is content"),
    findDevice:               () => AM6Module.findDevice(1),
    rebootDevice:             () => AM6Module.rebootDevice(),
    getTime:                  () => AM6Module.getTime(),
    setTargetRemind:          () => AM6Module.setTargetRemind(1, 500, 1500),
    getTargetRemind:          () => AM6Module.getTargetRemind(),
    setSedentaryRemind:       () => AM6Module.setSedentaryRemind(1, 1000, 1200),
    getSedentaryRemind:       () => AM6Module.getSedentaryRemind(),
    setRaiseToLightRemind:    () => AM6Module.setRaiseToLightRemind(1, 1000, 1200),
    getRaiseToLightRemind:    () => AM6Module.getRaiseToLightRemind(),
    setDoNotDisturbMode:      () => AM6Module.setDoNotDisturbMode(1, 1000, 1200),
    getDoNotDisturbMode:      () => AM6Module.getDoNotDisturbMode(),
    setWearHand:              () => AM6Module.setWearHand(1),
    getWearHand:              () => AM6Module.getWearHand(),
    setAlarmClockList:        () => AM6Module.setAlarmClockList(1),
    getAlarmClockList:        () => AM6Module.getAlarmClockList(),
    startBind:                () => AM6Module.startBind(),
    bindUserSuccess:          () => AM6Module.bindUserSuccess([0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]),
    bindUserFail:             () => AM6Module.bindUserFail(),
    unBindUser:               () => AM6Module.unBindUser([0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]),
    readySyncData:            () => AM6Module.readySyncData(),
    getDailyData:             () => AM6Module.getDailyData(),
    getStepData:              () => AM6Module.getStepData(),
    getSleepData:             () => AM6Module.getSleepData(),
    getHeartRateData:         () => AM6Module.getHeartRateData(),
    getBloodOxygenData:       () => AM6Module.getBloodOxygenData(),
    getActivityData:          () => AM6Module.getActivityData(),
    deleteData:               () => AM6Module.deleteData(1),
    disconnect:            (mac) => AM6Module.disconnect(mac),
  },
}