import { AM6Module } from '@ihealth/ihealthlibrary-react-native';

export default {
  apis: {
    getAllConnectedDevices:   () => AM6Module.getAllConnectedDevices(),
    getDeviceInfoAndSyncTime: (mac) => AM6Module.getDeviceInfoAndSyncTime(mac, true),
    setUserInfo:              (mac) => AM6Module.setUserInfo(mac, "test123456", 1, 30, 170, 60),
    setPhonePlatform:         (mac) => AM6Module.setPhonePlatform(mac),
    notifyMessage:            (mac) => AM6Module.notifyMessage(mac, 1660926758875, 1, 1, "This is title", "This is content"),
    findDevice:               (mac) => AM6Module.findDevice(mac, 1),
    rebootDevice:             (mac) => AM6Module.rebootDevice(mac),
    getTime:                  (mac) => AM6Module.getTime(mac),
    setTargetRemind:          (mac) => AM6Module.setTargetRemind(mac, true, 500, 1500),
    getTargetRemind:          (mac) => AM6Module.getTargetRemind(mac),
    setSedentaryRemind:       (mac) => AM6Module.setSedentaryRemind(mac, 1, 1000, 1200),
    getSedentaryRemind:       (mac) => AM6Module.getSedentaryRemind(mac),
    setRaiseToLightRemind:    (mac) => AM6Module.setRaiseToLightRemind(mac, 1, 1000, 1200),
    getRaiseToLightRemind:    (mac) => AM6Module.getRaiseToLightRemind(mac),
    setDoNotDisturbMode:      (mac) => AM6Module.setDoNotDisturbMode(mac, 1, 1000, 1200),
    getDoNotDisturbMode:      (mac) => AM6Module.getDoNotDisturbMode(mac),
    setWearHand:              (mac) => AM6Module.setWearHand(mac, 1),
    getWearHand:              (mac) => AM6Module.getWearHand(mac),
    setAlarmClockList:        (mac) => AM6Module.setAlarmClockList(mac, "1:1-1-1-1-1-1-1:1200;1:1-1-1-1-1-1-1:1400"),
    getAlarmClockList:        (mac) => AM6Module.getAlarmClockList(mac),
    startBind:                (mac) => AM6Module.startBind(mac),
    bindUserSuccess:          (mac) => AM6Module.bindUserSuccess(mac, "test123456"),
    bindUserFail:             (mac) => AM6Module.bindUserFail(mac),
    unBindUser:               (mac) => AM6Module.unBindUser(mac, "test123456"),
    readySyncData:            (mac) => AM6Module.readySyncData(mac),
    getDailyData:             (mac) => AM6Module.getDailyData(mac),
    getStepData:              (mac) => AM6Module.getStepData(mac),
    getSleepData:             (mac) => AM6Module.getSleepData(mac),
    getHeartRateData:         (mac) => AM6Module.getHeartRateData(mac),
    getBloodOxygenData:       (mac) => AM6Module.getBloodOxygenData(mac),
    getActivityData:          (mac) => AM6Module.getActivityData(mac),
    deleteData:               (mac) => AM6Module.deleteData(mac, 1),
    disconnect:               (mac) => AM6Module.disconnect(mac),
  },
}